blank_issues_enabled: false
contact_links:
  - name: "Questions & Support"
    url: "https://github.com/dinmukhamednurkaliyev"
    about: "Please ask questions in Discussions instead of opening Issues."
