name: "Standard / Labeler"

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  run:
    name: "Labeler: Run"
    runs-on: ubuntu-latest
    steps:
      - name: "Repository: Checkout"
        uses: actions/checkout@v6.0.1

      - name: "Labeler: Sync"
        uses: actions/labeler@v6.0.1
        with:
          sync-labels: true
          configuration-path: .github/configurations/pull_request_labeler.yaml
